Fix for Staking API
maticnetwork/subgraphs pull request #14
Opened 2020-12-31 12:41 UTC by itzmeanjan

Added fields & handler functions, which were required by staking API

2020-12-31 13:19 UTC, jdkanani requested changes

2020-12-31 13:19 UTC, jdkanani commented on root/src/mappings/staking-info.ts
> +  validator.delegatedStake = validator.delegatedStake.plus(event.params.amount)
Smart!

2020-12-31 13:19 UTC, jdkanani commented on root/schema.graphql
> +  # issue : In handler function how should we be able to
We can process the template in the `prepare:<network>` package json script, which can add a JSON file with all addresses. Mapping files can use those addresses directly. The mapping function can fetch the owner using a web3 call from a subgraph and save it in an entity (a subgraph supports web3 calls).

2020-12-31 14:45 UTC, itzmeanjan commented on root/schema.graphql
> +  # issue : In handler function how should we be able to
Yes, we can do that. Ok, I'll make that change.

2021-01-01 06:09 UTC, jdkanani approved these changes

2021-01-01 06:09 UTC, merged