Tracking Plasma Token Mappings
maticnetwork/subgraphs pull request #20
Opened 2021-01-20 05:43 UTC by itzmeanjan

## changes

This PR attempts to make Plasma & POS token mapping tracking easier while distinguishing them, using binary value.

2021-01-20 07:20 UTC, Meshugah approved these changes
The registry contract on goerli has a couple of reverted transactions. Just pointing it out: https://goerli.etherscan.io/tx/0x936576973320be3057ea8de858efc0baed2fb1e96dbd8bd09146e837ebc0701a.

2021-01-20 08:38 UTC, reddyismav approved these changes

2021-01-21 03:34 UTC, itzmeanjan commented
> The registry contract on goerli has a couple of reverted transactions. Just pointing it out: https://goerli.etherscan.io/tx/0x936576973320be3057ea8de858efc0baed2fb1e96dbd8bd09146e837ebc0701a.

Doesn't seem those concern us.

2021-01-27 10:00 UTC, reddyismav approved these changes

2021-01-27 10:04 UTC, jdkanani requested changes

2021-01-27 10:04 UTC, jdkanani commented on root/src/mappings/registry.ts
> +  let id = 'token-mapping-' + event.params.rootToken.toHexString()
What happens when we have token mapped on both plasma and pos?

We should add test in id:

```suggestion
  let id = 'plasma-token-mapping-' + event.params.rootToken.toHexString()
```

2021-01-27 10:04 UTC, jdkanani commented on root/subgraph.template.yaml
> +        - TokenMapped
```suggestion
        - TokenMapping
```

2021-01-27 10:53 UTC, itzmeanjan commented on root/subgraph.template.yaml
> +        - TokenMapped
Fixed

2021-01-27 10:54 UTC, itzmeanjan commented on root/src/mappings/registry.ts
> +  let id = 'token-mapping-' + event.params.rootToken.toHexString()
Fixed issue, using different `id` for Plasma & PoS root tokens.

2021-01-27 10:54 UTC, itzmeanjan commented on root/src/mappings/registry.ts
> +  let id = 'token-mapping-' + event.params.rootToken.toHexString()
Thanks for pointing it out @jdkanani 🙌

2021-01-27 11:48 UTC, jdkanani approved these changes

2021-01-27 14:55 UTC, merged