Read token type from contract, for Plasma Tokens
maticnetwork/subgraphs pull request #21
Opened 2021-01-27 18:16 UTC by itzmeanjan

This PR attempts to add support for subgraphs trying to read state of `isERC721` mapping in Registry contract, so that we can store token type in subgraph when processing Plasma token mapping request.

2021-01-27 18:20 UTC, jdkanani requested changes

2021-01-27 18:20 UTC, jdkanani commented on root/src/mappings/registry.ts
> +  entity.tokenType = (registry.isERC721(event.params.rootToken) ? '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a' : '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0
Shouldn't we just store string? "ERC20" or "ERC721"?

2021-01-27 18:21 UTC, itzmeanjan commented on root/src/mappings/registry.ts
> +  entity.tokenType = (registry.isERC721(event.params.rootToken) ? '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a' : '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0
I'm doing it this way to keep this in sync with its POS counterpart.

2021-01-27 18:23 UTC, reddyismav commented on root/src/mappings/registry.ts
> +  entity.tokenType = (registry.isERC721(event.params.rootToken) ? '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a' : '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0
POS is done in the similar way.

2021-01-28 05:41 UTC, jdkanani commented on root/src/mappings/registry.ts
> +  entity.tokenType = (registry.isERC721(event.params.rootToken) ? '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a' : '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0
Okay should work for now.

2021-01-28 05:41 UTC, jdkanani approved these changes

2021-01-28 05:51 UTC, merged