Fix `tokenType` issue & decrease stake when `DelegatorUnstaked ` happens
maticnetwork/subgraphs pull request #23
Opened 2021-02-01 12:41 UTC by itzmeanjan

## Changes

- Convert `tokenType` from Bytes to String
- Also decrease delegator's stake when `DelegatorUnstaked ` happens

2021-02-01 13:39 UTC, Meshugah commented on root/src/mappings/rootchain-manager.ts
> +  entity.tokenType = event.params.tokenType.toHex()
Why is this necessary?

2021-02-01 13:39 UTC, Meshugah approved these changes

2021-02-01 13:49 UTC, jdkanani requested changes

2021-02-01 13:49 UTC, jdkanani commented on root/src/mappings/registry.ts
> +  entity.tokenType = (registry.isERC721(event.params.rootToken) ? '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a' : '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0
Did we test it locally?

2021-02-01 14:02 UTC, itzmeanjan commented on root/src/mappings/rootchain-manager.ts
> +  entity.tokenType = event.params.tokenType.toHex()
Data received from event is in `Bytes` form

2021-02-01 14:02 UTC, itzmeanjan commented on root/src/mappings/registry.ts
> +  entity.tokenType = (registry.isERC721(event.params.rootToken) ? '0x73ad2146b3d3a286642c794379d750360a2d53a3459a11b3e5d6cc900f55f44a' : '0x8ae85d849167ff996c04040c44924fd364217285e4cad818292c7ac37c0
Yes we did, it's working.

2021-02-01 14:03 UTC, jdkanani commented on root/src/mappings/rootchain-manager.ts
> +  entity.tokenType = event.params.tokenType.toHex()
But didn't we save it as String?

2021-02-04 05:42 UTC, itzmeanjan commented
Attempt to decode state sync data & store decoded form in graphQL entity.

2021-02-04 05:43 UTC, itzmeanjan commented
Attempt to figure out signer list who signed certain checkpoint from txInput for `submitHeaderBlock`.

2021-02-04 06:40 UTC, itzmeanjan commented
Deployment details added.

2021-02-04 07:06 UTC, jdkanani requested changes

2021-02-04 07:06 UTC, jdkanani commented on root/config/mainnet.json
> +    "decoder": {
Can we change to some meaning ful name now? Like - decoderForPoSPortalData?

2021-02-04 07:23 UTC, reddyismav requested changes

2021-02-04 07:23 UTC, reddyismav commented on root/abis/Decoder.json
> +[
Can the decoder be specified as what its decoding. Name or comment about it would do. 
Will be benefecial for people who are gonna work on it in future.

2021-02-04 07:24 UTC, reddyismav commented on root/abis/Decoder.json
> +[
JDs comment name of decoderPosPortalData should do.. I didnt see his review before the comment.

2021-02-04 07:26 UTC, reddyismav approved these changes

2021-02-04 11:13 UTC, itzmeanjan commented on root/config/mainnet.json
> +    "decoder": {
Sure we can do so.

2021-02-04 11:21 UTC, itzmeanjan commented on root/config/mainnet.json
> +    "decoder": {
Done.

2021-02-04 15:12 UTC, jdkanani approved these changes

2021-02-04 15:47 UTC, merged