Compute validator power & rewards for each checkpoint
maticnetwork/subgraphs pull request #25
Opened 2021-02-05 05:12 UTC by itzmeanjan

## Changes

- For each checkpoint, power & reward of that checkpoint signers, to be computed & stored
- This can be used as historical entry for each checkpoint sent from L2 to L1

2021-02-06 05:16 UTC, jdkanani requested changes

2021-02-06 05:16 UTC, jdkanani commented on root/src/mappings/checkpoint.ts
> +import { Address, BigDecimal, BigInt, Bytes, Value } from '@graphprotocol/graph-ts'
Can we fix lint errors?

2021-02-06 05:17 UTC, jdkanani approved these changes

2021-02-06 05:19 UTC, jdkanani commented
Reward calculation has a max cap on the checkpoint. Can we also take it into consideration? cc @imyourm8

2021-02-06 14:06 UTC, Meshugah approved these changes

2021-02-08 06:20 UTC, itzmeanjan reviewed
Done

2021-02-08 06:20 UTC, itzmeanjan commented on root/src/mappings/checkpoint.ts
> +import { Address, BigDecimal, BigInt, Bytes, Value } from '@graphprotocol/graph-ts'
Done

2021-02-10 05:15 UTC, itzmeanjan commented
We're reverting back to previous state. Please read more in  #26

2021-02-21 08:33 UTC, itzmeanjan commented
Closing this PR, not required.

2021-02-21 08:33 UTC, closed without merging