Plasma exit events
maticnetwork/subgraphs pull request #5
Opened 2020-11-19 05:23 UTC by itzmeanjan

## changes

- Subgraphs for catching :arrow_down: events, emitted during Plasma Exit
   - `ExitStarted`
   - `ExitCancelled`
   - `ExitUpdated`
   - `Withdraw`

2020-11-19 05:28 UTC, jdkanani approved these changes

2020-11-19 09:05 UTC, jdkanani requested changes

2020-11-19 09:05 UTC, jdkanani commented on root/src/mappings/withdrawManager.ts
> +  entity.save()
Shouldn't we delete exit started entity instead of creating a new entity?

2020-11-19 09:06 UTC, jdkanani requested changes

2020-11-19 09:06 UTC, jdkanani commented on root/src/mappings/withdrawManager.ts
> +}
Same for exit update. Shouldn't we update the existing entity instead of creating a new one?

2020-11-19 09:27 UTC, itzmeanjan commented on root/src/mappings/withdrawManager.ts
> +}
In this can, we can keep `age` field empty primarily in entity, when exit started & update it later. Is it ?

2020-11-19 09:27 UTC, itzmeanjan commented on root/src/mappings/withdrawManager.ts
> +  entity.save()
Yes, we should do it. Let me fix this.

2020-11-20 09:26 UTC, itzmeanjan commented
- Requested changes implemented @jdkanani .
- Also added more fields _( timestamp, txHash )_ in entities. 
- Not sure what to do with [`TokenMapped`](https://github.com/maticnetwork/pos-portal/blob/6adc4464bfb7b1c2b289fc5c9f69b28498283463/contracts/root/RootChainManager/IRootChainManager.sol#L4) event, due to the fact tokens can be remapped, in that case what to use as `id` for graphQL entity, so that we get to update old entry. We need to have two way one - to - one mapping for this.

**@jdkanani interested in learning about your opinion for last point.**

2020-11-20 10:16 UTC, jdkanani approved these changes

2020-11-23 06:50 UTC, itzmeanjan commented
@jdkanani added subgraph for tracking token mapping events.

2020-11-23 08:30 UTC, jdkanani commented
@itzmeanjan Is it working locally?

2020-11-23 11:30 UTC, Meshugah approved these changes
Looks good to me. I've had trouble running it locally but that's it.

2020-12-09 06:13 UTC, jdkanani approved these changes

2020-12-09 06:13 UTC, merged